<!DOCTYPE html>
<html>
<head>
    <title>{{ __('Rental Terms and Conditions') }}</title>
    <style>
        body { font-family: 'Times New Roman', serif; font-size: 12px; line-height: 1.5; text-align: justify; }
        h1 { text-align: center; font-size: 18px; text-transform: uppercase; margin-bottom: 30px; }
        h2 { font-size: 14px; margin-top: 20px; margin-bottom: 10px; text-transform: uppercase; }
        p { margin-bottom: 10px; }
        ul { margin-bottom: 10px; }
        li { margin-bottom: 5px; }
        .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #666; border-top: 1px solid #ccc; padding-top: 10px; }
    </style>
</head>
<body>
    <h1>{{ __('General Terms and Conditions for Vehicle Rental') }}</h1>

    <p>{{ __('This contract establishes the general conditions that will govern the rental of vehicles through the platform. By accepting these terms, the Lessee agrees to comply with all the clauses described herein.') }}</p>

    <h2>1. {{ __('Object of the Contract') }}</h2>
    <p>{{ __('The Lessor grants the Lessee the temporary use of the vehicle described in the rental application, for the agreed period and under the stipulated conditions.') }}</p>

    <h2>2. {{ __('Vehicle Delivery and Return') }}</h2>
    <p>2.1. {{ __('The vehicle is delivered in perfect working and clean condition, with all its accessories and documentation.') }}</p>
    <p>2.2. {{ __('The Lessee is obliged to return the vehicle in the same condition in which it was received, except for normal wear and tear, on the agreed date and time.') }}</p>
    <p>2.3. <strong>{{ __('Delays in return') }}:</strong> {{ __('If the vehicle is not returned on the agreed date and time, a penalty will be applied for each hour of delay, equivalent to double the proportional daily rate.') }}</p>
    <p>2.4. <strong>{{ __('Legal Actions') }}:</strong> {{ __('If 24 hours have elapsed since the end date of the contract and the vehicle has not been returned and there is no justified communication from the Lessee, the Lessor reserves the right to file the corresponding complaints for misappropriation with the competent authorities.') }}</p>

    <h2>3. {{ __('Use of the Vehicle') }}</h2>
    <p>3.1. {{ __('The Lessee agrees to use the vehicle diligently and respecting the current traffic regulations.') }}</p>
    <p>3.2. {{ __('It is expressly prohibited to') }}:</p>
    <ul>
        <li>{{ __('Sublease the vehicle or assign its use to unauthorized third parties.') }}</li>
        <li>{{ __('Use the vehicle for the transport of dangerous or illegal goods.') }}</li>
        <li>{{ __('Drive under the influence of alcohol, drugs or medications that alter driving ability.') }}</li>
        <li>{{ __('Participate in races, competitions or speed tests.') }}</li>
        <li>{{ __('Leave the national territory without express written authorization from the Lessor.') }}</li>
    </ul>

    <h2>4. {{ __('Maintenance and Breakdowns') }}</h2>
    <p>4.1. {{ __('The Lessee must periodically check the oil, water and tire pressure levels.') }}</p>
    <p>4.2. {{ __('In the event of a mechanical breakdown, the Lessee must stop the vehicle immediately and contact the roadside assistance service and the Lessor.') }}</p>

    <h2>5. {{ __('Insurance and Liability') }}</h2>
    <p>5.1. {{ __('The vehicle has mandatory civil liability insurance.') }}</p>
    <p>5.2. {{ __('The Lessee shall be liable for any damage caused to the vehicle by negligence, misuse or breach of the conditions of this contract, as well as for damages not covered by the insurance policy.') }}</p>
    <p>5.3. {{ __('The Lessee shall be responsible for all traffic fines and penalties imposed during the rental period.') }}</p>

    <h2>6. {{ __('Fuel Policy') }}</h2>
    <p>{{ __('The vehicle is delivered with a certain level of fuel and must be returned with the same level. Otherwise, the amount of the missing fuel plus a refueling service charge will be charged.') }}</p>

    <h2>7. {{ __('Contract Termination') }}</h2>
    <p>{{ __('Failure to comply with any of the clauses of this contract will entitle the Lessor to terminate it unilaterally and demand the immediate return of the vehicle, without prejudice to any claims for damages that may arise.') }}</p>

    <h2>8. {{ __('Jurisdiction') }}</h2>
    <p>{{ __('For any controversy that may arise from the interpretation or fulfillment of this contract, the parties submit to the Courts and Tribunals of the place of delivery of the vehicle, expressly waiving any other jurisdiction that may correspond to them.') }}</p>

    <div class="footer">
        <p>{{ __('Document generated by the Vehicle Rental Platform. All rights reserved.') }}</p>
    </div>
</body>
</html>
