<!DOCTYPE html>
<html>
<head>
    <title>{{ __('Sale Terms and Conditions') }}</title>
    <style>
        body { font-family: 'Times New Roman', serif; font-size: 12px; line-height: 1.5; text-align: justify; }
        h1 { text-align: center; font-size: 18px; text-transform: uppercase; margin-bottom: 30px; }
        h2 { font-size: 14px; margin-top: 20px; margin-bottom: 10px; text-transform: uppercase; }
        p { margin-bottom: 10px; }
        .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #666; border-top: 1px solid #ccc; padding-top: 10px; }
    </style>
</head>
<body>
    <h1>{{ __('Vehicle Sale Contract') }}</h1>

    <p>{{ __('This document establishes the terms and conditions under which the sale of the vehicle is carried out through the platform.') }}</p>

    <h2>1. {{ __('Object') }}</h2>
    <p>{{ __('The Seller transfers ownership of the vehicle described in the offer to the Buyer, who accepts it and agrees to pay the agreed price.') }}</p>

    <h2>2. {{ __('Price and Payment') }}</h2>
    <p>2.1. {{ __('The purchase price is that agreed in the accepted offer.') }}</p>
    <p>2.2. {{ __('Payment will be made through the means enabled on the platform.') }}</p>

    <h2>3. {{ __('Vehicle Condition') }}</h2>
    <p>3.1. {{ __('The Seller declares that the vehicle is free of charges and encumbrances.') }}</p>
    <p>3.2. {{ __('The Buyer declares to know the current condition of the vehicle and accepts it in the conditions in which it is found ("as is").') }}</p>

    <h2>4. {{ __('Delivery') }}</h2>
    <p>{{ __('The delivery of the vehicle and the necessary documentation for the transfer will take place once payment is confirmed.') }}</p>

    <h2>5. {{ __('Warranty') }}</h2>
    <p>{{ __('The sale between individuals is governed by the Civil Code, unless otherwise agreed. If the seller is a professional, the Law on Guarantees in the Sale of Consumer Goods will apply.') }}</p>

    <h2>6. {{ __('Applicable Legislation') }}</h2>
    <p>{{ __('For any divergence that may arise, the parties submit to the current legislation and the competent courts.') }}</p>

    <div class="footer">
        <p>{{ __('Document generated by the Vehicle Platform.') }}</p>
    </div>
</body>
</html>
